# Generated by Django 3.2 on 2022-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_logout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_dt', models.DateTimeField()),
                ('logout_dt', models.DateTimeField()),
            ],
        ),
    ]
