# Generated by Django 3.2 on 2022-05-01 03:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnidata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicadminID', models.CharField(default='#', max_length=10)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'lgbtqia2s+')], default='#', max_length=10)),
                ('responsible', models.CharField(default='#', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='adminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldresponible', models.CharField(default='#', max_length=50)),
                ('adminID', models.CharField(default='#', max_length=10)),
                ('firstname', models.CharField(default='#', max_length=50)),
                ('lastname', models.CharField(default='#', max_length=50)),
                ('phone', models.CharField(default='#', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='alumnidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumniID', models.CharField(default='#', max_length=10)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'lgbtqia2s+')], default='#', max_length=10)),
                ('address', models.TextField(default='#', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='alumniList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldstudy', models.CharField(default='#', max_length=50)),
                ('yearGraduated', models.IntegerField(default=2543)),
                ('studentID', models.CharField(default='#', max_length=10)),
                ('firstname', models.CharField(default='#', max_length=50)),
                ('lastname', models.CharField(default='#', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='assistantDean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistantDeanID', models.CharField(default='#', max_length=10)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='assistantDeanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistantDeanID', models.CharField(default='#', max_length=10)),
                ('firstname', models.CharField(default='#', max_length=50)),
                ('lastname', models.CharField(default='#', max_length=50)),
                ('phone', models.CharField(default='#', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='#', max_length=10)),
                ('university', models.CharField(default='#', max_length=255)),
                ('faculty', models.CharField(default='#', max_length=255)),
                ('major', models.CharField(default='#', max_length=255)),
                ('country', models.CharField(default='#', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='fieldstudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyField', models.CharField(default='#', max_length=80)),
                ('studyMajor', models.CharField(default='#', max_length=80)),
                ('studyMinor', models.CharField(default='#', max_length=80)),
                ('yearStart', models.IntegerField(default=2543)),
                ('yearGraduate', models.IntegerField(default=2547)),
                ('gpa', models.FloatField(default=3.5, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default='#', max_length=255)),
                ('organizeType', models.CharField(default='#', max_length=255)),
                ('department', models.CharField(default='#', max_length=255)),
                ('jobTitle', models.CharField(default='#', max_length=255)),
                ('jobDesc', models.TextField(default='#', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='#', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieveTitle', models.CharField(default='#', max_length=150)),
                ('desc', models.TextField(default='#', max_length=2000)),
                ('achieveDate', models.DateField(default=datetime.date.today, max_length=10)),
                ('alumniuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='login_logout',
        ),
        migrations.AddField(
            model_name='job',
            name='alumniuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AddField(
            model_name='fieldstudy',
            name='alumniuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='alumniuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AddField(
            model_name='assistantdean',
            name='assistantDeanName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AddField(
            model_name='alumnidata',
            name='alumniuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AddField(
            model_name='academicadmin',
            name='academicadminName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
    ]
