# Generated by Django 3.2 on 2022-04-22 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0003_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('achievementID', models.CharField(default='#', max_length=4, primary_key=True, serialize=False)),
                ('achieveTitle', models.CharField(default='#', max_length=50)),
                ('desc', models.TextField(default='#', max_length=2000)),
                ('achieveDate', models.DateField(default=datetime.date.today, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='alumnifaculty',
            fields=[
                ('facultyID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('studyField', models.CharField(default='#', max_length=50)),
                ('studyMajor', models.CharField(default='#', max_length=30)),
                ('studyMinor', models.CharField(default='#', max_length=30)),
                ('yearStart', models.IntegerField(default=2543)),
                ('yearGraduate', models.IntegerField(default=2547)),
                ('gpa', models.FloatField(default=3.5, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='alumnijob',
            fields=[
                ('jobID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('organization', models.CharField(default='#', max_length=30)),
                ('organizeType', models.CharField(default='#', max_length=10)),
                ('department', models.CharField(default='#', max_length=20)),
                ('jobTitle', models.CharField(default='#', max_length=30)),
                ('jobDesc', models.CharField(default='#', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='furthereducation',
            fields=[
                ('universityID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('degree', models.CharField(default='#', max_length=10)),
                ('university', models.CharField(default='#', max_length=50)),
                ('faculty', models.CharField(default='#', max_length=50)),
                ('major', models.CharField(default='#', max_length=50)),
                ('country', models.CharField(default='#', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='assistantDean',
            fields=[
                ('assistantDeanID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('assistantDeanName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('alumniID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'lgbtqia2s+')], default='#', max_length=10)),
                ('address', models.TextField(default='#', max_length=2500)),
                ('achieve', models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achievement')),
                ('alumniName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
                ('faculty', models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.alumnifaculty')),
                ('furtherEdu', models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.furthereducation')),
                ('job', models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.alumnijob')),
            ],
        ),
        migrations.CreateModel(
            name='academicadmin',
            fields=[
                ('academicadminID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'lgbtqia2s+')], default='#', max_length=10)),
                ('details', models.CharField(default='#', max_length=80)),
                ('academicadminName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
    ]
