# Generated by Django 3.2 on 2022-04-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0004_academicadmin_achievement_alumni_alumnifaculty_alumnijob_assistantdean_furthereducation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='achieve',
        ),
    ]
