# Generated by Django 3.2 on 2022-04-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0005_remove_alumni_achieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='achieve',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achievement'),
        ),
    ]
