# Generated by Django 3.2 on 2022-04-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0008_auto_20220422_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='achieve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achievement'),
        ),
    ]
