# Generated by Django 3.2 on 2022-04-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0009_alter_alumni_achieve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='achieve',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='furtherEdu',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='job',
        ),
    ]
