# Generated by Django 3.2 on 2022-04-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0010_auto_20220422_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='faculty',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.alumnifaculty'),
        ),
    ]
