# Generated by Django 3.2 on 2022-04-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0013_alumni_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='achieves',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achievement'),
        ),
    ]
