# Generated by Django 3.2 on 2022-04-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0014_alumni_achieves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='achieves',
        ),
    ]
