# Generated by Django 3.2 on 2022-04-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0015_remove_alumni_achieves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='achievement',
        ),
    ]
