# Generated by Django 3.2 on 2022-04-22 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0016_delete_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='achieve',
            fields=[
                ('achieveID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('achieveTitle', models.CharField(default='#', max_length=50)),
                ('desc', models.TextField(default='#', max_length=2000)),
                ('achieveDate', models.DateField(default=datetime.date.today, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='achievement',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achieve'),
        ),
    ]
