# Generated by Django 3.2 on 2022-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0017_auto_20220422_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnijob',
            name='jobDesc',
            field=models.TextField(default='#', max_length=255),
        ),
    ]
