# Generated by Django 3.2 on 2022-04-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0018_alter_alumnijob_jobdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='fieldsofstudy',
            fields=[
                ('studyFieldID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('studyField', models.CharField(default='#', max_length=50)),
                ('studyMajor', models.CharField(default='#', max_length=30)),
                ('studyMinor', models.CharField(default='#', max_length=30)),
                ('yearStart', models.IntegerField(default=2543)),
                ('yearGraduate', models.IntegerField(default=2547)),
                ('gpa', models.FloatField(default=3.5, max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='alumni',
            name='faculty',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.fieldsofstudy'),
        ),
        migrations.DeleteModel(
            name='alumnifaculty',
        ),
    ]
