# Generated by Django 3.2 on 2022-04-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0020_fieldsofstudy_alumniname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsofstudy',
            name='alumniName',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='education',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='job',
        ),
        migrations.DeleteModel(
            name='achieve',
        ),
        migrations.DeleteModel(
            name='alumnijob',
        ),
        migrations.DeleteModel(
            name='fieldsofstudy',
        ),
        migrations.DeleteModel(
            name='furthereducation',
        ),
    ]
