# Generated by Django 3.2 on 2022-04-22 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0021_auto_20220422_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='furthereducation',
            fields=[
                ('universityID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('degree', models.CharField(default='#', max_length=10)),
                ('university', models.CharField(default='#', max_length=50)),
                ('faculty', models.CharField(default='#', max_length=50)),
                ('major', models.CharField(default='#', max_length=50)),
                ('country', models.CharField(default='#', max_length=20)),
                ('alumniName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='fieldsofstudy',
            fields=[
                ('studyFieldID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('studyField', models.CharField(default='#', max_length=50)),
                ('studyMajor', models.CharField(default='#', max_length=30)),
                ('studyMinor', models.CharField(default='#', max_length=30)),
                ('yearStart', models.IntegerField(default=2543)),
                ('yearGraduate', models.IntegerField(default=2547)),
                ('gpa', models.FloatField(default=3.5, max_length=4)),
                ('alumniName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='alumnijob',
            fields=[
                ('jobID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('organization', models.CharField(default='#', max_length=30)),
                ('organizeType', models.CharField(default='#', max_length=10)),
                ('department', models.CharField(default='#', max_length=20)),
                ('jobTitle', models.CharField(default='#', max_length=30)),
                ('jobDesc', models.TextField(default='#', max_length=255)),
                ('alumniName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='achieve',
            fields=[
                ('achieveID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('achieveTitle', models.CharField(default='#', max_length=50)),
                ('desc', models.TextField(default='#', max_length=2000)),
                ('achieveDate', models.DateField(default=datetime.date.today, max_length=10)),
                ('alumniName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='achievement',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.achieve'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='education',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.furthereducation'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='job',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.alumnijob'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='studyField',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.fieldsofstudy'),
        ),
    ]
