# Generated by Django 3.2 on 2022-04-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0022_auto_20220422_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achieve',
            name='alumniName',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='alumniName',
        ),
        migrations.RemoveField(
            model_name='alumnijob',
            name='alumniName',
        ),
        migrations.RemoveField(
            model_name='fieldsofstudy',
            name='alumniName',
        ),
        migrations.RemoveField(
            model_name='furthereducation',
            name='alumniName',
        ),
    ]
