# Generated by Django 3.2 on 2022-04-22 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0024_auto_20220422_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('universityID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('degree', models.CharField(default='#', max_length=10)),
                ('university', models.CharField(default='#', max_length=50)),
                ('faculty', models.CharField(default='#', max_length=50)),
                ('major', models.CharField(default='#', max_length=50)),
                ('country', models.CharField(default='#', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fieldstudy',
            fields=[
                ('studyFieldID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('studyField', models.CharField(default='#', max_length=50)),
                ('studyMajor', models.CharField(default='#', max_length=30)),
                ('studyMinor', models.CharField(default='#', max_length=30)),
                ('yearStart', models.IntegerField(default=2543)),
                ('yearGraduate', models.IntegerField(default=2547)),
                ('gpa', models.FloatField(default=3.5, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('jobID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('organization', models.CharField(default='#', max_length=30)),
                ('organizeType', models.CharField(default='#', max_length=10)),
                ('department', models.CharField(default='#', max_length=20)),
                ('jobTitle', models.CharField(default='#', max_length=30)),
                ('jobDesc', models.TextField(default='#', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='success',
            fields=[
                ('achieveID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('achieveTitle', models.CharField(default='#', max_length=50)),
                ('desc', models.TextField(default='#', max_length=2000)),
                ('achieveDate', models.DateField(default=datetime.date.today, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='achieve',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.success'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='educations',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.education'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='jobs',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.job'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='studyin',
            field=models.ForeignKey(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.fieldstudy'),
        ),
    ]
