# Generated by Django 3.2 on 2022-04-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0026_alumni_alumniname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='alumniname',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
    ]
