# Generated by Django 3.2 on 2022-04-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0029_alumni_alumname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='alumname',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumniID',
            field=models.CharField(default='6209656062', max_length=10, primary_key=True, serialize=False),
        ),
    ]
