# Generated by Django 3.2 on 2022-04-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0031_rename_alumname_alumni_alumniname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='alumniName',
        ),
    ]
