# Generated by Django 3.2 on 2022-04-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0032_remove_alumni_alumniname'),
    ]

    operations = [
        migrations.CreateModel(
            name='autotable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(default='#', max_length=10)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile')),
            ],
        ),
    ]
