# Generated by Django 3.2 on 2022-04-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0033_autotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='alumniuser',
            field=models.OneToOneField(default='#', on_delete=django.db.models.deletion.CASCADE, to='alumnidata.profile'),
        ),
    ]
