# Generated by Django 3.2 on 2022-04-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0034_alumni_alumniuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumni',
        ),
    ]
