# Generated by Django 3.2 on 2022-04-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0037_auto_20220425_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnidata',
            name='achieve',
        ),
        migrations.RemoveField(
            model_name='alumnidata',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='alumnidata',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='alumnidata',
            name='studyin',
        ),
    ]
