# Generated by Django 3.2 on 2022-04-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0038_auto_20220425_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotable',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='alumnidata',
        ),
        migrations.DeleteModel(
            name='autotable',
        ),
    ]
