# Generated by Django 3.2 on 2022-04-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0040_alumnidata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumnidata',
        ),
    ]
