# Generated by Django 3.2 on 2022-04-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0041_delete_alumnidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicadmin',
            name='academicadminName',
        ),
        migrations.RemoveField(
            model_name='assistantdean',
            name='assistantDeanName',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='fieldstudy',
        ),
        migrations.DeleteModel(
            name='job',
        ),
        migrations.DeleteModel(
            name='login_logout',
        ),
        migrations.DeleteModel(
            name='success',
        ),
        migrations.DeleteModel(
            name='academicadmin',
        ),
        migrations.DeleteModel(
            name='assistantDean',
        ),
    ]
