# Generated by Django 3.2 on 2022-04-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0043_academicadmin_alumnidata_assistantdean_education_fieldstudy_job_success'),
    ]

    operations = [
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='fieldstudy',
        ),
        migrations.DeleteModel(
            name='job',
        ),
        migrations.DeleteModel(
            name='success',
        ),
    ]
