# Generated by Django 3.2 on 2022-04-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0045_education_fieldstudy_job_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='universityID',
        ),
        migrations.RemoveField(
            model_name='fieldstudy',
            name='studyFieldID',
        ),
    ]
