# Generated by Django 3.2 on 2022-04-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0046_auto_20220428_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicadmin',
            name='details',
        ),
        migrations.AddField(
            model_name='academicadmin',
            name='responsible',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
