# Generated by Django 3.2 on 2022-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnidata', '0048_adminlist_alumnilist_assistantdeanlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldstudy',
            name='studyField',
            field=models.CharField(default='#', max_length=80),
        ),
        migrations.AlterField(
            model_name='fieldstudy',
            name='studyMajor',
            field=models.CharField(default='#', max_length=80),
        ),
        migrations.AlterField(
            model_name='fieldstudy',
            name='studyMinor',
            field=models.CharField(default='#', max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobTitle',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='organizeType',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='success',
            name='achieveTitle',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
